import { AppLogic } from "applogic.slint";

export component ColorPatch inherits VerticalLayout {
    in property <color> color: #990000;
    alignment: start;
    padding-bottom: 4px;
    spacing: 14px;

    Rectangle {
        width: 70px;
        height: self.width;
        border-radius: self.width / 2;
        border-color: white;
        border-width: 5px;

        background: parent.color;
    }
    ctext:= Text {
        horizontal-alignment: center;
        color: #bbbbbb;
        font-size: 13px;
        text: AppLogic.format-color(parent.color);
    }
}